### ISSUE TITLE
"help improve this page" should redirect users to the repository

### ISSUE THREAD

**Issue by marcocastignoli** [nileorg/documentation#2]

**Comment by huhn511** [comment]
With this link, `Please {% github_edit_link "help improve this page" %}.` users within the team can edit the page directly. Github users which are not in the team, get redirected to the "fork this repo" page. 

I think that's nice - because most edits will come from our team. Normal users have to fork it an create a pull request. Maybe we should describe the workflow somehow. 

What do you think? @marcocastignoli

**Comment by marcocastignoli** [comment]
I like your solution :+1:
